nome1 = input()
nome2 = input()
nome3 = input()
nome4 = input()
nome5 = input()
nome6 = input()
nome7 = input()
nome8 = input()
nome9 = input()
nome10 = input()

print (nome3)
print (nome7)
print (nome9)